import { useMemo, useState } from "react";
import { Alert, Modal, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { useLocalSearchParams } from "expo-router";
import { useAddGroupMember, useGroup, useGroupMembers, useRemoveGroupMember, useStudents } from "@/api/hooks";
import { Avatar, Button, Card, EmptyState, ErrorState, LoadingState, PageHeader, Screen, SearchBar, SectionHeader } from "@/components";
import { colors, spacing, typography } from "@/theme";

export default function GroupDetailScreen() {
  const { groupId } = useLocalSearchParams<{ groupId: string }>(); const group = useGroup(groupId); const members = useGroupMembers(groupId); const students = useStudents(); const add = useAddGroupMember(); const remove = useRemoveGroupMember();
  const [open, setOpen] = useState(false); const [search, setSearch] = useState(""); const [selected, setSelected] = useState<string[]>([]);
  const memberIds = useMemo(() => new Set((members.data ?? []).map((s: { id: string }) => s.id)), [members.data]); const candidates = (students.data ?? []).filter((s) => !memberIds.has(s.id) && `${s.first_name} ${s.last_name}`.toLowerCase().includes(search.toLowerCase()));
  const confirm = async () => { try { await Promise.all(selected.map((studentId) => add.mutateAsync({ groupId, studentId }))); setSelected([]); setOpen(false); } catch { Alert.alert("Could not add students", "Please try again."); } };
  if (group.isLoading || members.isLoading || students.isLoading) return <Screen><LoadingState /></Screen>;
  if (group.isError || members.isError || students.isError || !group.data) return <Screen><ErrorState onRetry={() => { void group.refetch(); void members.refetch(); void students.refetch(); }} /></Screen>;
  const memberList = members.data ?? [];
  return <Screen><PageHeader eyebrow="GROUP" title={group.data.name} /><ScrollView contentContainerStyle={styles.content}><Card style={styles.summary}><Text style={styles.number}>{memberList.length}</Text><Text style={styles.label}>active students</Text><Text style={styles.hint}>Shared work and fees apply while a student is active in this group.</Text></Card><SectionHeader title="Members" action={<Button variant="ghost" onPress={() => setOpen(true)}>+ Add Student</Button>} />{memberList.length ? memberList.map((student) => <Card style={styles.member} key={student.id}><Avatar name={`${student.first_name} ${student.last_name}`} /><View style={styles.copy}><Text style={styles.rowTitle}>{student.first_name} {student.last_name}</Text><Text style={styles.meta}>{student.grade ?? "Student"}{student.student_number ? ` · Roll ${student.student_number}` : ""}</Text></View><Pressable onPress={() => Alert.alert("Remove student?", "Their history stays intact. They will no longer receive future group items.", [{ text: "Cancel", style: "cancel" }, { text: "Remove", style: "destructive", onPress: () => void remove.mutateAsync({ groupId, studentId: student.id }) }])}><Text style={styles.remove}>Remove</Text></Pressable></Card>) : <EmptyState icon="👥" title="No students yet" message="Add students to start sharing work and fees." />}<Modal visible={open} transparent animationType="slide"><View style={styles.modal}><View style={styles.sheet}><Text style={styles.sheetTitle}>Add students</Text><SearchBar value={search} onChangeText={setSearch} placeholder="Search students" /><ScrollView contentContainerStyle={styles.candidates}>{candidates.map((student) => { const checked = selected.includes(student.id); return <Pressable key={student.id} onPress={() => setSelected((v) => checked ? v.filter((id) => id !== student.id) : [...v, student.id])}><Card style={[styles.member, checked && styles.selected]}><Avatar name={`${student.first_name} ${student.last_name}`} size={36} /><View style={styles.copy}><Text style={styles.rowTitle}>{student.first_name} {student.last_name}</Text><Text style={styles.meta}>{student.grade ?? "Student"}</Text></View><Text style={styles.check}>{checked ? "✓" : "+"}</Text></Card></Pressable>; })}</ScrollView><View style={styles.actions}><Button variant="ghost" onPress={() => setOpen(false)}>Cancel</Button><Button disabled={!selected.length || add.isPending} onPress={() => void confirm()}>Add {selected.length} student{selected.length === 1 ? "" : "s"}</Button></View></View></View></Modal></ScrollView></Screen>;
}
const styles = StyleSheet.create({ content: { gap: spacing.md, paddingBottom: spacing.xxl }, summary: { backgroundColor: colors.primaryLight, padding: spacing.lg }, number: { ...typography.display, color: colors.primary, fontSize: 32 }, label: { ...typography.heading, fontSize: 15 }, hint: { ...typography.caption, marginTop: spacing.sm }, member: { alignItems: "center", flexDirection: "row", padding: spacing.md }, copy: { flex: 1, marginHorizontal: spacing.md }, rowTitle: { ...typography.heading, fontSize: 15 }, meta: { ...typography.caption, marginTop: 3 }, remove: { color: colors.red, fontSize: 13, fontWeight: "800" }, modal: { backgroundColor: "rgba(20,28,40,.35)", flex: 1, justifyContent: "flex-end" }, sheet: { backgroundColor: colors.paper, borderTopLeftRadius: 28, borderTopRightRadius: 28, maxHeight: "90%", padding: spacing.xl }, sheetTitle: { ...typography.display, fontSize: 24, marginBottom: spacing.md }, candidates: { gap: spacing.sm, paddingVertical: spacing.md }, selected: { borderColor: colors.primary, borderWidth: 2 }, check: { color: colors.primary, fontSize: 22, fontWeight: "800" }, actions: { flexDirection: "row", gap: spacing.sm, justifyContent: "flex-end" } });
