import { useState } from "react";
import { Alert, FlatList, Modal, Pressable, StyleSheet, Text, View } from "react-native";
import { MaterialCommunityIcons } from "@expo/vector-icons";
import { router } from "expo-router";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { groupsApi } from "@/api/groups";
import { Button, Card, EmptyState, ErrorState, IconButton, LoadingState, PageHeader, Screen, TuiroInput } from "@/components";
import { colors, spacing, typography } from "@/theme";

export default function GroupsScreen() {
  const queryClient = useQueryClient(); const [open, setOpen] = useState(false); const [name, setName] = useState("");
  const groups = useQuery({ queryKey: ["groups"], queryFn: groupsApi.list });
  const create = useMutation({ mutationFn: groupsApi.create, onSuccess: () => { void queryClient.invalidateQueries({ queryKey: ["groups"] }); setName(""); setOpen(false); } });
  const submit = async () => { if (!name.trim()) return Alert.alert("Name required", "Enter a name for this group."); try { await create.mutateAsync(name.trim()); } catch { Alert.alert("Unable to create group", "Please try again."); } };
  if (groups.isLoading) return <Screen><LoadingState /></Screen>;
  if (groups.isError) return <Screen><ErrorState onRetry={() => void groups.refetch()} /></Screen>;
  return <Screen><PageHeader eyebrow="GROUPS" title="Your batches" right={<IconButton label="Create group" tone="primary" onPress={() => setOpen(true)} icon={<MaterialCommunityIcons name="plus" size={22} color="#fff" />} />} /><Text style={styles.intro}>Shared work, fees and schedules live once at the group level.</Text><FlatList contentContainerStyle={styles.list} data={groups.data} keyExtractor={(item) => item.id} ListEmptyComponent={<EmptyState icon="👥" title="No groups yet" message="Create a batch, then add its students." />} renderItem={({ item }) => <Pressable onPress={() => router.push(`/groups/${item.id}` as never)}><Card style={styles.group}><View style={styles.icon}><MaterialCommunityIcons name="account-group-outline" size={24} color={colors.primary} /></View><View style={styles.copy}><Text style={styles.name}>{item.name}</Text><Text style={styles.meta}>{item.student_count} student{item.student_count === 1 ? "" : "s"}{item.next_class ? ` · ${item.next_class.start_time}` : " · No schedule"}</Text></View><MaterialCommunityIcons name="chevron-right" size={22} color={colors.muted} /></Card></Pressable>} /><Modal transparent visible={open} animationType="slide"><View style={styles.modal}><View style={styles.sheet}><Text style={styles.title}>Create group</Text><TuiroInput autoFocus label="Group name" placeholder="Grade 12 · Morning batch" value={name} onChangeText={setName} /><View style={styles.actions}><Button variant="ghost" onPress={() => setOpen(false)}>Cancel</Button><Button disabled={create.isPending} onPress={() => void submit()}>{create.isPending ? "Creating..." : "Create group"}</Button></View></View></View></Modal></Screen>;
}
const styles = StyleSheet.create({ intro: { ...typography.body, color: colors.muted, marginTop: -spacing.lg }, list: { gap: spacing.sm, paddingVertical: spacing.lg, flexGrow: 1 }, group: { alignItems: "center", flexDirection: "row", padding: spacing.md }, icon: { alignItems: "center", backgroundColor: colors.primaryLight, borderRadius: 20, height: 42, justifyContent: "center", width: 42 }, copy: { flex: 1, marginHorizontal: spacing.md }, name: { ...typography.heading, fontSize: 16 }, meta: { ...typography.caption, marginTop: 3 }, modal: { backgroundColor: "rgba(20,28,40,.35)", flex: 1, justifyContent: "flex-end" }, sheet: { backgroundColor: colors.paper, borderTopLeftRadius: 28, borderTopRightRadius: 28, padding: spacing.xl }, title: { ...typography.display, fontSize: 24 }, actions: { flexDirection: "row", gap: spacing.sm, justifyContent: "flex-end", marginTop: spacing.lg } });
