import { useQuery } from "@tanstack/react-query";
import { ScrollView, StyleSheet, Text, View } from "react-native";
import { reportsApi } from "@/api/reports";
import { Card, ErrorState, LoadingState, PageHeader, Screen, SectionHeader } from "@/components";
import { colors, spacing, typography } from "@/theme";

type FeeReport = { collected_amount: string | number; pending_amount: string | number; payment_count: number };
type AttendanceReport = { total_records: number; present_records: number; attendance_percentage: number };
const money = (value: string | number) => new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format(Number(value) || 0);
export default function ReportsScreen() {
    const fees = useQuery({ queryKey: ["report-fees"], queryFn: reportsApi.fees }); const attendance = useQuery({ queryKey: ["report-attendance"], queryFn: reportsApi.attendance });
    if (fees.isLoading || attendance.isLoading) return <Screen><LoadingState /></Screen>;
    if (fees.isError || attendance.isError) return <Screen><ErrorState onRetry={() => { void fees.refetch(); void attendance.refetch(); }} /></Screen>;
    const finance = fees.data as FeeReport; const roll = attendance.data as AttendanceReport;
    return <Screen><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.content}><PageHeader eyebrow="INSIGHTS" title="Reports" /><Text style={styles.subtitle}>A clear picture of your centre’s progress.</Text><Card style={styles.finance}><Text style={styles.kicker}>FEE COLLECTION</Text><Text style={styles.primaryNumber}>{money(finance.collected_amount)}</Text><Text style={styles.lightCopy}>collected across {finance.payment_count} payment{finance.payment_count === 1 ? "" : "s"}</Text><View style={styles.financeGrid}><View><Text style={styles.lightLabel}>PENDING</Text><Text style={styles.lightValue}>{money(finance.pending_amount)}</Text></View><View style={styles.divider} /><View><Text style={styles.lightLabel}>COLLECTED</Text><Text style={styles.lightValue}>{money(finance.collected_amount)}</Text></View></View></Card><SectionHeader title="Attendance" /><Card><View style={styles.attendanceTop}><View><Text style={styles.attendanceNumber}>{roll.attendance_percentage}%</Text><Text style={styles.attendanceCopy}>overall attendance</Text></View><View style={styles.ring}><Text style={styles.ringText}>{roll.present_records}</Text><Text style={styles.ringCaption}>present</Text></View></View><View style={styles.track}><View style={[styles.fill, { width: `${Math.min(100, Math.max(0, roll.attendance_percentage))}%` }]} /></View><Text style={styles.detail}>{roll.present_records} present records from {roll.total_records} marked sessions.</Text></Card></ScrollView></Screen>;
}
const styles = StyleSheet.create({ content: { gap: spacing.lg, paddingBottom: spacing.xxl, paddingTop: spacing.lg }, subtitle: { ...typography.body, marginTop: -spacing.lg }, finance: { backgroundColor: colors.ink, marginTop: spacing.md }, kicker: { color: "#b9c8ef", fontSize: 11, fontWeight: "800", letterSpacing: 1.1 }, primaryNumber: { color: colors.white, fontSize: 32, fontWeight: "800", marginTop: spacing.sm }, lightCopy: { color: "#dce6ff", fontSize: 13, marginTop: 2 }, financeGrid: { flexDirection: "row", marginTop: spacing.xl }, lightLabel: { color: "#afc1eb", fontSize: 10, fontWeight: "800", letterSpacing: 0.8 }, lightValue: { color: colors.white, fontSize: 16, fontWeight: "800", marginTop: 4 }, divider: { backgroundColor: "rgba(255,255,255,0.18)", marginHorizontal: spacing.xl, width: 1 }, attendanceTop: { alignItems: "center", flexDirection: "row", justifyContent: "space-between" }, attendanceNumber: { ...typography.heading, fontSize: 30 }, attendanceCopy: { ...typography.caption, marginTop: 2 }, ring: { alignItems: "center", backgroundColor: colors.sageSoft, borderRadius: 28, height: 56, justifyContent: "center", width: 56 }, ringText: { color: colors.sage, fontSize: 15, fontWeight: "800" }, ringCaption: { color: colors.sage, fontSize: 9, fontWeight: "700" }, track: { backgroundColor: colors.line, borderRadius: 99, height: 9, marginTop: spacing.xl, overflow: "hidden" }, fill: { backgroundColor: colors.sage, borderRadius: 99, height: "100%" }, detail: { ...typography.caption, marginTop: spacing.sm } });
