"use client";
import { FormEvent, useEffect, useState } from "react";
import { api } from "@/lib/api";
import { useTerm } from "@/components/use-term";
type Group = { id: string; name: string; kind: string; description?: string };
export default function GroupsPage() {
  const { term } = useTerm(); const [groups, setGroups] = useState<Group[]>([]); const [error, setError] = useState(""); const [open, setOpen] = useState(false);
  const load = () => api<Group[]>("/api/v2/groups").then(setGroups).catch((e: Error) => setError(e.message)); useEffect(() => { void load(); }, []);
  async function create(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); try { await api("/api/v2/groups", { method: "POST", body: JSON.stringify({ name: data.get("name"), kind: data.get("kind"), description: data.get("description") || null }) }); event.currentTarget.reset(); setOpen(false); load(); } catch (e) { setError((e as Error).message); } }
  return <section><div className="flex items-center justify-between"><div><h1 className="text-2xl font-semibold">{term("group", true)}</h1><p className="mt-1 text-sm text-slate-500">Organize people into teams, classes, batches, and departments.</p></div><button onClick={() => setOpen(!open)} className="rounded-lg bg-blue-600 px-3 py-2 text-sm text-white">Add {term("group", false)}</button></div>{open && <form onSubmit={create} className="mt-6 grid gap-3 rounded-xl border p-4 md:grid-cols-2"><input required name="name" placeholder="Name" className="rounded border p-2"/><select name="kind" className="rounded border p-2"><option value="team">Team</option><option value="department">Department</option><option value="class">Class</option><option value="batch">Batch</option></select><textarea name="description" placeholder="Description" className="rounded border p-2 md:col-span-2"/><button className="w-fit rounded bg-blue-600 px-3 py-2 text-sm text-white">Save</button></form>}{error && <p role="alert" className="mt-4 text-sm text-red-600">{error}</p>}<div className="mt-6 grid gap-3 md:grid-cols-2">{groups.map((group) => <article key={group.id} className="rounded-xl border p-4"><h2 className="font-medium">{group.name}</h2><p className="mt-1 text-sm text-slate-500">{group.kind}{group.description ? ` · ${group.description}` : ""}</p></article>)}{!groups.length && <p className="rounded-xl border p-6 text-sm text-slate-500">No {term("group", true).toLowerCase()} yet.</p>}</div></section>;
}
