import { FlatList, StyleSheet, Text, View } from "react-native";
import { MaterialCommunityIcons } from "@expo/vector-icons";
import { router } from "expo-router";
import { useGroupFeeAttention } from "@/api/hooks";
import { Avatar, Badge, Card, EmptyState, ErrorState, IconButton, LoadingState, PageHeader, Screen } from "@/components";
import { colors, spacing, typography } from "@/theme";

const tone: Record<string, "success" | "warning" | "danger" | "neutral"> = { PAID: "success", PARTIAL: "warning", OVERDUE: "danger", PENDING: "warning" };
const money = (value: string | number) => new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format(Number(value) || 0);
export default function FeesScreen() {
    const query = useGroupFeeAttention();
    if (query.isLoading) return <Screen><LoadingState /></Screen>;
    if (query.isError) return <Screen><ErrorState onRetry={() => void query.refetch()} /></Screen>;
    const fees = query.data ?? []; const outstanding = fees.reduce((total, fee) => total + Number(fee.outstanding_amount), 0); const overdue = fees.filter((fee) => fee.status === "OVERDUE");
    return <Screen><PageHeader eyebrow="FINANCE" title="Fees" right={<IconButton label="Create fee" onPress={() => router.push("/fees/collect")} tone="primary" icon={<MaterialCommunityIcons name="plus" color="#fff" size={22} />} />} /><Text style={styles.subtitle}>One group fee, clear per-student follow-up.</Text><View style={styles.balance}><Text style={styles.balanceLabel}>TOTAL OUTSTANDING</Text><Text style={styles.balanceAmount}>{money(outstanding)}</Text><View style={styles.balanceFooter}><Text style={styles.balanceMeta}>{fees.length} student payment{fees.length === 1 ? "" : "s"} need attention</Text><View style={styles.overdue}><MaterialCommunityIcons name="alert-circle-outline" color={colors.red} size={16} /><Text style={styles.overdueText}>{overdue.length} overdue</Text></View></View></View><View style={styles.section}><Text style={styles.sectionTitle}>Follow-up queue</Text><Text style={styles.sectionMeta}>Each row is a student</Text></View><FlatList showsVerticalScrollIndicator={false} refreshing={query.isRefetching} onRefresh={() => void query.refetch()} contentContainerStyle={styles.list} data={fees} keyExtractor={(item) => `${item.fee_id}-${item.student_id}`} ListEmptyComponent={<EmptyState icon="🎉" title="You're all caught up" message="No outstanding fees need attention right now." />} renderItem={({ item, index }) => <View style={[styles.row, index === 0 && styles.firstRow]}><Avatar name={item.student_name} size={index === 0 ? 48 : 38} /><View style={styles.copy}><Text style={styles.name}>{item.student_name}</Text><Text style={styles.meta}>{item.source} fee · Due {item.due_date}</Text></View><View style={styles.amountBlock}><Text style={styles.amount}>{money(item.outstanding_amount)}</Text><Badge tone={tone[item.status] ?? "neutral"}>{item.status}</Badge></View></View>} /></Screen>;
}
const styles = StyleSheet.create({ subtitle: { ...typography.body, marginTop: -spacing.lg }, balance: { backgroundColor: colors.primary, borderRadius: 22, marginTop: spacing.xl, padding: spacing.xl }, balanceLabel: { color: "#B9D3C5", fontSize: 10, fontWeight: "800", letterSpacing: 1.2 }, balanceAmount: { color: colors.white, fontFamily: typography.display.fontFamily, fontSize: 40, fontWeight: "800", letterSpacing: -1, marginTop: spacing.sm }, balanceFooter: { alignItems: "center", flexDirection: "row", justifyContent: "space-between", marginTop: spacing.lg }, balanceMeta: { color: "#E5F0EA", fontSize: 12 }, overdue: { alignItems: "center", backgroundColor: colors.redSoft, borderRadius: 999, flexDirection: "row", gap: 4, paddingHorizontal: spacing.sm, paddingVertical: 5 }, overdueText: { color: colors.red, fontSize: 11, fontWeight: "800" }, section: { alignItems: "baseline", flexDirection: "row", justifyContent: "space-between", marginTop: spacing.xl }, sectionTitle: { ...typography.heading, fontSize: 18 }, sectionMeta: { ...typography.body, fontSize: 11 }, list: { flexGrow: 1, paddingBottom: spacing.xxl, paddingTop: spacing.md }, row: { alignItems: "center", borderBottomColor: colors.line, borderBottomWidth: 1, flexDirection: "row", paddingVertical: spacing.md }, firstRow: { backgroundColor: colors.white, borderColor: colors.line, borderRadius: 16, borderWidth: 1, marginBottom: spacing.sm, padding: spacing.md }, copy: { flex: 1, marginHorizontal: spacing.md }, name: { ...typography.heading, fontSize: 15 }, meta: { ...typography.body, fontSize: 12, marginTop: 3 }, amountBlock: { alignItems: "flex-end", gap: spacing.xs }, amount: { color: colors.ink, fontSize: 16, fontWeight: "800" } });
