import { FlatList, StyleSheet, Text, View } from "react-native";
import { MaterialCommunityIcons } from "@expo/vector-icons";
import { router } from "expo-router";
import { useGroupFeeAttention } from "@/api/hooks";
import { Avatar, Badge, Card, EmptyState, ErrorState, IconButton, LoadingState, PageHeader, Screen } from "@/components";
import { colors, spacing, typography } from "@/theme";

const tone: Record<string, "success" | "warning" | "danger" | "neutral"> = { PAID: "success", PARTIAL: "warning", OVERDUE: "danger", PENDING: "warning" };
const money = (value: string | number) => new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format(Number(value) || 0);
export default function FeesScreen() {
    const query = useGroupFeeAttention();
    if (query.isLoading) return <Screen><LoadingState /></Screen>;
    if (query.isError) return <Screen><ErrorState onRetry={() => void query.refetch()} /></Screen>;
    const fees = query.data ?? []; const outstanding = fees.reduce((total, fee) => total + Number(fee.outstanding_amount), 0); const overdue = fees.filter((fee) => fee.status === "OVERDUE");
    return <Screen><PageHeader eyebrow="FINANCE" title="Fees" right={<IconButton label="Create fee" onPress={() => router.push("/fees/collect")} tone="primary" icon={<MaterialCommunityIcons name="plus" color="#fff" size={22} />} />} /><Text style={styles.subtitle}>Create once for a group; payments remain tracked per student.</Text><Card style={styles.balance}><Text style={styles.balanceLabel}>TOTAL OUTSTANDING</Text><Text style={styles.balanceAmount}>{money(outstanding)}</Text><View style={styles.balanceFooter}><View><Text style={styles.balanceMeta}>{fees.length} student payment{fees.length === 1 ? "" : "s"} need attention</Text></View><View style={styles.overdue}><MaterialCommunityIcons name="alert-circle-outline" color={colors.red} size={16} /><Text style={styles.overdueText}>{overdue.length} overdue</Text></View></View></Card><View style={styles.section}><Text style={styles.sectionTitle}>Needs attention</Text><Text style={styles.sectionMeta}>Each row is a student</Text></View><FlatList showsVerticalScrollIndicator={false} refreshing={query.isRefetching} onRefresh={() => void query.refetch()} contentContainerStyle={styles.list} data={fees} keyExtractor={(item) => `${item.fee_id}-${item.student_id}`} ListEmptyComponent={<EmptyState icon="🎉" title="You're all caught up" message="No outstanding fees need attention right now." />} renderItem={({ item }) => <Card style={styles.row}><Avatar name={item.student_name} size={42} /><View style={styles.copy}><Text style={styles.name}>{item.student_name}</Text><Text style={styles.meta}>{item.source} fee · Due {item.due_date}</Text></View><View style={styles.amountBlock}><Text style={styles.amount}>{money(item.outstanding_amount)}</Text><Badge tone={tone[item.status] ?? "neutral"}>{item.status}</Badge></View></Card>} /></Screen>;
}
const styles = StyleSheet.create({ subtitle: { ...typography.body, marginTop: -spacing.lg }, balance: { backgroundColor: colors.ink, marginTop: spacing.xl, padding: spacing.xl }, balanceLabel: { color: "#b6c5ed", fontSize: 11, fontWeight: "800", letterSpacing: 1.2 }, balanceAmount: { color: colors.white, fontSize: 32, fontWeight: "800", letterSpacing: -1, marginTop: spacing.sm }, balanceFooter: { alignItems: "center", flexDirection: "row", justifyContent: "space-between", marginTop: spacing.lg }, balanceMeta: { color: "#dce6ff", fontSize: 13 }, overdue: { alignItems: "center", backgroundColor: "#fff0ef", borderRadius: 999, flexDirection: "row", gap: 4, paddingHorizontal: spacing.sm, paddingVertical: 5 }, overdueText: { color: colors.red, fontSize: 11, fontWeight: "800" }, section: { alignItems: "baseline", flexDirection: "row", justifyContent: "space-between", marginTop: spacing.xl }, sectionTitle: { ...typography.heading, fontSize: 18 }, sectionMeta: { ...typography.body, fontSize: 11 }, list: { flexGrow: 1, gap: spacing.sm, paddingBottom: spacing.xxl, paddingTop: spacing.md }, row: { alignItems: "center", flexDirection: "row", padding: spacing.md }, copy: { flex: 1, marginHorizontal: spacing.md }, name: { ...typography.heading, fontSize: 15 }, meta: { ...typography.body, fontSize: 12, marginTop: 3 }, amountBlock: { alignItems: "flex-end", gap: spacing.xs }, amount: { color: colors.ink, fontSize: 16, fontWeight: "800" } });
