import { MaterialCommunityIcons } from "@expo/vector-icons";
import { router } from "expo-router";
import { ReactNode } from "react";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";

import { Screen } from "@/components";
import { useAuthStore } from "@/store/auth";
import { colors, radius, shadow, spacing, typography } from "@/theme";

const icons: Record<string, keyof typeof MaterialCommunityIcons.glyphMap> = { Homework: "book-open-page-variant-outline", Tests: "clipboard-text-outline", Schedule: "calendar-clock-outline", Parents: "account-group-outline", Teachers: "account-tie-outline", Classes: "google-classroom", Receipts: "receipt-text-outline", Reports: "chart-line", Notifications: "bell-outline", Subscription: "star-outline", Settings: "cog-outline", Help: "help-circle-outline" };
const routes: Record<string, string> = { Homework: "/homework", Tests: "/tests", Schedule: "/schedule", Parents: "/parents", Teachers: "/teachers", Classes: "/classes", Receipts: "/receipts", Reports: "/reports", Notifications: "/notifications", Subscription: "/subscription", Settings: "/settings", Help: "/help" };

export default function MoreScreen() { const signOut = useAuthStore((state) => state.signOut); return <Screen><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.content}><View style={styles.header}><View><Text style={styles.eyebrow}>WORKSPACE</Text><Text style={styles.title}>More</Text><Text style={styles.subtitle}>Your centre, organised.</Text></View><MaterialCommunityIcons name="tune-variant" color={colors.primary} size={28} /></View><MenuGroup title="Academic" items={["Homework", "Tests", "Schedule"]} /><MenuGroup title="People" items={["Parents", "Teachers", "Classes"]} /><MenuGroup title="Business" items={["Receipts", "Reports", "Notifications", "Subscription"]} /><MenuGroup title="System" items={["Settings", "Help"]} /><Pressable accessibilityRole="button" style={styles.signOut} onPress={() => void signOut().then(() => router.replace("/auth/login"))}><MaterialCommunityIcons name="logout" color={colors.red} size={20} /><Text style={styles.signOutText}>Sign out</Text></Pressable></ScrollView></Screen>; }
function MenuGroup({ title, items }: { title: string; items: string[] }) { return <View style={styles.group}><Text style={styles.groupTitle}>{title}</Text><View style={styles.menu}>{items.map((item) => <MenuRow key={item} title={item} icon={icons[item]} onPress={routes[item] ? () => router.push(routes[item] as never) : undefined} />)}</View></View>; }
function MenuRow({ title, icon, onPress }: { title: string; icon: keyof typeof MaterialCommunityIcons.glyphMap; onPress?: () => void }) { return <Pressable accessibilityRole="button" onPress={onPress} style={({ pressed }) => [styles.row, pressed && styles.pressed]}><View style={styles.iconWrap}><MaterialCommunityIcons name={icon} color={colors.primary} size={21} /></View><Text style={styles.rowTitle}>{title}</Text><MaterialCommunityIcons name="chevron-right" color={colors.muted} size={21} /></Pressable>; }
const styles = StyleSheet.create({ content: { paddingTop: spacing.lg, paddingBottom: spacing.xxl, gap: spacing.xl }, header: { alignItems: "center", flexDirection: "row", justifyContent: "space-between" }, eyebrow: { ...typography.label, color: colors.coral, letterSpacing: 1.2 }, title: { ...typography.display, marginTop: spacing.xs }, subtitle: { ...typography.body, marginTop: spacing.xs }, group: { gap: spacing.sm }, groupTitle: { ...typography.label, color: colors.muted, letterSpacing: 1, textTransform: "uppercase" }, menu: { backgroundColor: colors.white, borderRadius: radius.md, ...shadow }, row: { alignItems: "center", borderBottomColor: colors.line, borderBottomWidth: StyleSheet.hairlineWidth, flexDirection: "row", minHeight: 64, paddingHorizontal: spacing.md }, pressed: { backgroundColor: colors.featureBlue }, iconWrap: { alignItems: "center", backgroundColor: colors.featureBlue, borderRadius: radius.sm, height: 38, justifyContent: "center", marginRight: spacing.md, width: 38 }, rowTitle: { color: colors.ink, flex: 1, fontSize: 15, fontWeight: "700" }, signOut: { alignItems: "center", flexDirection: "row", gap: spacing.sm, justifyContent: "center", minHeight: 48 }, signOutText: { color: colors.red, fontSize: 15, fontWeight: "700" } });
