import { useState } from "react";
import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { useCreateGroupAssignment, useGroups, useStudents } from "@/api/hooks";
import { Button, Card, ErrorState, LoadingState, PageHeader, Screen, TuiroInput } from "@/components";
import { colors, spacing, typography } from "@/theme";

export default function HomeworkScreen() {
  const groups = useGroups(); const students = useStudents(); const create = useCreateGroupAssignment();
  const [individual, setIndividual] = useState(false); const [target, setTarget] = useState(""); const [title, setTitle] = useState(""); const [description, setDescription] = useState(""); const [dueDate, setDueDate] = useState("");
  if (groups.isLoading || students.isLoading) return <Screen><LoadingState /></Screen>;
  if (groups.isError || students.isError) return <Screen><ErrorState onRetry={() => { void groups.refetch(); void students.refetch(); }} /></Screen>;
  const choices = individual ? students.data ?? [] : groups.data ?? [];
  const submit = async () => { if (!target || !title) return Alert.alert("Complete the assignment", "Choose a group or individual student and enter a title."); try { await create.mutateAsync(individual ? { student_id: target, title, description, due_date: dueDate || undefined, type: "assignment" } : { group_id: target, title, description, due_date: dueDate || undefined, type: "assignment" }); Alert.alert("Homework added", individual ? "This is labelled Individual for the student." : "This will appear for every active group member."); setTarget(""); setTitle(""); setDescription(""); setDueDate(""); } catch { Alert.alert("Could not add homework", "Please try again."); } };
  return <Screen><ScrollView contentContainerStyle={styles.content}><PageHeader eyebrow="ACADEMICS" title="Add work" /><View style={styles.intro}><Text style={styles.introNumber}>01</Text><View><Text style={styles.introTitle}>Pick who this work is for</Text><Text style={styles.hint}>Groups are the default. Use individual only for an exception.</Text></View></View><View style={styles.mode}><Button variant={individual ? "ghost" : "secondary"} onPress={() => { setIndividual(false); setTarget(""); }}>Group</Button><Button variant={individual ? "secondary" : "ghost"} onPress={() => { setIndividual(true); setTarget(""); }}>Individual student</Button></View><Text style={styles.label}>{individual ? "Choose student" : "Choose group"}</Text>{choices.map((item, index) => <Pressable key={item.id} onPress={() => setTarget(item.id)}><Card style={[styles.choice, index === 0 && styles.choiceLead, target === item.id && styles.selected]}><Text style={styles.name}>{"name" in item ? item.name : `${item.first_name} ${item.last_name}`}</Text><Text style={styles.hint}>{"student_count" in item ? `${item.student_count} active students` : item.grade ?? "Student"}</Text></Card></Pressable>)}<View style={styles.formStart}><Text style={styles.formStep}>02 · THE WORK</Text><TuiroInput label="Title" value={title} onChangeText={setTitle} placeholder="Chapter revision" /><TuiroInput label="Description" value={description} onChangeText={setDescription} placeholder="What should students do?" multiline /><TuiroInput label="Due date (YYYY-MM-DD)" value={dueDate} onChangeText={setDueDate} placeholder="2026-10-01" /></View><Button disabled={create.isPending} onPress={() => void submit()}>{create.isPending ? "Adding..." : "Add work"}</Button></ScrollView></Screen>;
}
const styles = StyleSheet.create({ content: { gap: spacing.sm, paddingBottom: spacing.xxl, paddingTop: spacing.lg }, hint: { ...typography.body }, intro: { alignItems: "flex-start", backgroundColor: colors.primaryLight, borderRadius: 18, flexDirection: "row", gap: spacing.md, padding: spacing.lg }, introNumber: { color: colors.accent, fontFamily: typography.display.fontFamily, fontSize: 30, fontWeight: "800" }, introTitle: { ...typography.heading, fontSize: 17 }, label: { ...typography.label, marginTop: spacing.md }, mode: { flexDirection: "row", gap: spacing.sm }, choice: { padding: spacing.md }, choiceLead: { borderLeftColor: colors.accent, borderLeftWidth: 4, paddingVertical: spacing.lg }, selected: { borderColor: colors.primary, borderWidth: 2 }, name: { ...typography.heading, fontSize: 16 }, formStart: { borderTopColor: colors.line, borderTopWidth: 1, marginTop: spacing.md, paddingTop: spacing.lg }, formStep: { ...typography.label, color: colors.accent } });
