import { PropsWithChildren, ReactNode } from "react";
import { ActivityIndicator, Pressable, StyleSheet, Text, TextInput, TextInputProps, View } from "react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";

import { colors, radius, shadow, spacing, typography } from "@/theme";

export function Screen({ children }: PropsWithChildren) { const insets = useSafeAreaInsets(); return <View style={[styles.screen, { paddingTop: insets.top + spacing.sm, paddingBottom: insets.bottom + 94 }]}>{children}</View>; }
export function PageHeader({ eyebrow, title, right }: { eyebrow?: string; title: string; right?: ReactNode }) { return <View style={styles.header}><View style={styles.headerCopy}>{eyebrow && <Text style={styles.eyebrow}>{eyebrow}</Text>}<Text style={styles.title}>{title}</Text></View>{right}</View>; }
export function Card({ children, style }: PropsWithChildren<{ style?: object }>) { return <View style={[styles.card, style]}>{children}</View>; }
export function SectionHeader({ title, action }: { title: string; action?: ReactNode }) { return <View style={styles.sectionHeader}><Text style={styles.sectionTitle}>{title}</Text>{action}</View>; }
export function StatCard({ label, value, accent = colors.coral }: { label: string; value: string | number; accent?: string }) { return <Card style={{ borderLeftColor: accent, borderLeftWidth: 4 }}><Text style={styles.statValue}>{value}</Text><Text style={styles.statLabel}>{label}</Text></Card>; }
export function FeatureCard({ icon, title, subtitle, color = colors.featureBlue, onPress }: { icon: ReactNode; title: string; subtitle?: string; color?: string; onPress?: () => void }) { const visual = typeof icon === "string" ? <Text style={styles.featureIcon}>{icon}</Text> : <View style={styles.featureIcon}>{icon}</View>; return <Pressable accessibilityRole="button" onPress={onPress} style={({ pressed }) => [styles.featureCard, { backgroundColor: color }, pressed && styles.pressed]}>{visual}<Text style={styles.featureTitle}>{title}</Text>{subtitle && <Text style={styles.featureSubtitle}>{subtitle}</Text>}</Pressable>; }
export function IconButton({ icon, onPress, label, tone = "light" }: { icon: ReactNode; onPress?: () => void; label: string; tone?: "light" | "primary" }) { return <Pressable accessibilityRole="button" accessibilityLabel={label} onPress={onPress} style={({ pressed }) => [styles.iconButton, tone === "primary" ? styles.iconButtonPrimary : styles.iconButtonLight, pressed && styles.pressed]}>{icon}</Pressable>; }
export function Chip({ children, selected = false, onPress }: PropsWithChildren<{ selected?: boolean; onPress?: () => void }>) { return <Pressable onPress={onPress} style={[styles.chip, selected && styles.chipSelected]}><Text style={[styles.chipText, selected && styles.chipTextSelected]}>{children}</Text></Pressable>; }
export function Button({ children, onPress, variant = "primary", disabled = false }: PropsWithChildren<{ onPress?: () => void; variant?: "primary" | "secondary" | "ghost"; disabled?: boolean }>) { return <Pressable accessibilityRole="button" disabled={disabled} onPress={onPress} style={({ pressed }) => [styles.button, styles[`button_${variant}`], pressed && styles.pressed, disabled && styles.disabled]}><Text style={[styles.buttonText, variant === "primary" ? styles.buttonTextPrimary : styles.buttonTextSecondary]}>{children}</Text></Pressable>; }
export function TuiroInput({ label, error, ...props }: TextInputProps & { label?: string; error?: string }) { return <View style={styles.inputGroup}>{label && <Text style={styles.inputLabel}>{label}</Text>}<TextInput {...props} accessibilityLabel={props.accessibilityLabel ?? label ?? props.placeholder} placeholderTextColor={colors.muted} style={[styles.input, error && styles.inputError, props.style]} />{error && <Text style={styles.fieldError}>{error}</Text>}</View>; }
export function Badge({ children, tone = "neutral" }: PropsWithChildren<{ tone?: "neutral" | "success" | "warning" | "danger" }>) { return <View style={[styles.badge, styles[`badge_${tone}`]]}><Text style={styles.badgeText}>{children}</Text></View>; }
export function Avatar({ name, size = 44 }: { name: string; size?: number }) { const initials = name.trim().split(/\s+/).slice(0, 2).map((part) => part[0]).join("").toUpperCase(); return <View style={[styles.avatar, { width: size, height: size, borderRadius: size / 2 }]}><Text style={styles.avatarText}>{initials || "?"}</Text></View>; }
export function SearchBar({ value, onChangeText, placeholder = "Search" }: { value: string; onChangeText: (value: string) => void; placeholder?: string }) { return <View style={styles.search}><Text style={styles.searchIcon}>⌕</Text><TextInput accessibilityLabel={placeholder} value={value} onChangeText={onChangeText} placeholder={placeholder} placeholderTextColor={colors.muted} style={styles.searchInput} returnKeyType="search" /></View>; }
export function TuiroListItem({ leading, title, detail, trailing }: { leading?: ReactNode; title: string; detail?: string; trailing?: ReactNode }) { return <View style={styles.listItem}>{leading}<View style={styles.listCopy}><Text style={styles.listTitle} numberOfLines={1}>{title}</Text>{detail && <Text style={styles.listDetail} numberOfLines={2}>{detail}</Text>}</View>{trailing}</View>; }
export function EmptyState({ icon, title, message, action }: { icon: string; title: string; message: string; action?: ReactNode }) { return <View style={styles.empty}><Text style={styles.emptyIcon}>{icon}</Text><Text style={styles.emptyTitle}>{title}</Text><Text style={styles.emptyMessage}>{message}</Text>{action}</View>; }
export function LoadingState() { return <View accessibilityLabel="Loading" style={styles.center}><View style={styles.skeletonCard}><View style={styles.skeletonBlock} /><View style={styles.skeletonBlockShort} /></View><View style={styles.skeletonCard}><View style={styles.skeletonBlock} /><View style={styles.skeletonBlockShort} /></View><ActivityIndicator color={colors.primary} size="small" /></View>; }
export function ErrorState({ onRetry }: { onRetry: () => void }) { return <View style={styles.center}><View style={styles.errorIcon}><Text>!</Text></View><Text style={styles.errorTitle}>Something went wrong</Text><Text style={styles.errorMessage}>We couldn’t load this right now. Check your connection and try again.</Text><Button variant="secondary" onPress={onRetry}>Try again</Button></View>; }

const styles = StyleSheet.create({
    screen: { flex: 1, backgroundColor: colors.paper, paddingHorizontal: spacing.xl },
    header: { flexDirection: "row", alignItems: "flex-end", justifyContent: "space-between", paddingTop: spacing.lg, paddingBottom: spacing.xl },
    headerCopy: { flex: 1 }, eyebrow: { ...typography.label, color: colors.coral, letterSpacing: 1.2, marginBottom: spacing.sm }, title: typography.display,
    card: { backgroundColor: colors.white, borderRadius: radius.lg, padding: spacing.lg, ...shadow }, featureCard: { borderRadius: radius.lg, minHeight: 118, padding: spacing.lg, justifyContent: "space-between", flex: 1, minWidth: 145 }, featureIcon: { fontSize: 26, marginBottom: spacing.sm }, featureTitle: { ...typography.heading, fontSize: 16 }, featureSubtitle: { ...typography.body, fontSize: 12, marginTop: 2 }, sectionHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: spacing.md }, sectionTitle: typography.heading,
    statValue: { ...typography.heading, fontSize: 24 }, statLabel: { ...typography.body, fontSize: 13, marginTop: spacing.sm },
    button: { alignItems: "center", justifyContent: "center", minHeight: 52, borderRadius: radius.md, paddingHorizontal: spacing.xl }, button_primary: { backgroundColor: colors.primary }, button_secondary: { backgroundColor: colors.primaryLight }, button_ghost: { backgroundColor: "transparent" }, buttonText: { fontSize: 15, fontWeight: "800" }, buttonTextPrimary: { color: colors.white }, buttonTextSecondary: { color: colors.primary }, pressed: { opacity: 0.78, transform: [{ scale: 0.985 }] }, disabled: { opacity: 0.45 }, iconButton: { alignItems: "center", borderRadius: radius.pill, height: 46, justifyContent: "center", width: 46 }, iconButtonLight: { backgroundColor: colors.white, ...shadow }, iconButtonPrimary: { backgroundColor: colors.primary }, chip: { backgroundColor: colors.white, borderColor: colors.line, borderRadius: radius.pill, borderWidth: 1, paddingHorizontal: spacing.md, paddingVertical: spacing.sm }, chipSelected: { backgroundColor: colors.primary, borderColor: colors.primary }, chipText: { color: colors.inkSoft, fontSize: 13, fontWeight: "700" }, chipTextSelected: { color: colors.white }, inputGroup: { marginTop: spacing.md }, inputLabel: { ...typography.label, color: colors.ink, marginBottom: spacing.sm }, input: { backgroundColor: colors.white, borderColor: colors.line, borderRadius: radius.md, borderWidth: 1, color: colors.ink, fontSize: 16, minHeight: 52, paddingHorizontal: spacing.lg }, inputError: { borderColor: colors.red }, fieldError: { color: colors.red, fontSize: 12, marginTop: spacing.xs },
    badge: { alignSelf: "flex-start", borderRadius: radius.pill, paddingHorizontal: spacing.sm, paddingVertical: 5 }, badge_neutral: { backgroundColor: colors.line }, badge_success: { backgroundColor: colors.sageSoft }, badge_warning: { backgroundColor: colors.amberSoft }, badge_danger: { backgroundColor: colors.redSoft }, badgeText: { color: colors.inkSoft, fontSize: 11, fontWeight: "800" }, avatar: { alignItems: "center", justifyContent: "center", backgroundColor: colors.featureBlue }, avatarText: { color: colors.primary, fontWeight: "800" }, search: { alignItems: "center", flexDirection: "row", backgroundColor: colors.white, borderRadius: radius.md, paddingHorizontal: spacing.md, minHeight: 50, ...shadow }, searchIcon: { color: colors.primary, fontSize: 24, marginRight: spacing.sm }, searchInput: { flex: 1, color: colors.ink, fontSize: 15 }, listItem: { alignItems: "center", backgroundColor: colors.white, borderRadius: radius.md, flexDirection: "row", minHeight: 68, padding: spacing.md, ...shadow }, listCopy: { flex: 1, marginHorizontal: spacing.md }, listTitle: { ...typography.heading, fontSize: 15 }, listDetail: { ...typography.body, fontSize: 13, marginTop: spacing.xs }, skeletonBlock: { backgroundColor: colors.line, borderRadius: radius.sm, height: 16, marginBottom: spacing.md, width: 160 }, skeletonBlockShort: { backgroundColor: colors.line, borderRadius: radius.sm, height: 12, marginBottom: spacing.lg, width: 100 },
    empty: { alignItems: "center", paddingVertical: spacing.xxxl, paddingHorizontal: spacing.lg }, emptyIcon: { fontSize: 34, marginBottom: spacing.md }, emptyTitle: { ...typography.heading, textAlign: "center" }, emptyMessage: { ...typography.body, textAlign: "center", marginTop: spacing.sm, marginBottom: spacing.lg }, center: { flex: 1, alignItems: "center", justifyContent: "center", gap: spacing.md }, errorIcon: { alignItems: "center", backgroundColor: colors.redSoft, borderRadius: 24, height: 48, justifyContent: "center", width: 48 }, errorTitle: { ...typography.heading, color: colors.red }, errorMessage: { ...typography.body, maxWidth: 260, textAlign: "center" }, skeletonCard: { backgroundColor: colors.white, borderRadius: radius.lg, padding: spacing.lg, width: "100%", ...shadow },
});
