import { ScrollView, StyleSheet, Text, View } from "react-native";
import { useSubscription, useSubscriptionPlans } from "@/api/hooks";
import { Badge, Card, EmptyState, ErrorState, LoadingState, PageHeader, Screen } from "@/components";
import { colors, spacing, typography } from "@/theme";

export default function SubscriptionScreen() {
    const subscription = useSubscription(); const plans = useSubscriptionPlans();
    if (subscription.isLoading || plans.isLoading) return <Screen><LoadingState /></Screen>;
    if (subscription.isError || plans.isError) return <Screen><ErrorState onRetry={() => { void subscription.refetch(); void plans.refetch(); }} /></Screen>;
    const current = subscription.data;
    return <Screen><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.content}><PageHeader eyebrow="WORKSPACE" title="Subscription" /><Card style={styles.current}><View><Text style={styles.currentLabel}>CURRENT PLAN</Text><Text style={styles.currentName}>{current?.plan?.name ?? "No plan"}</Text><Text style={styles.currentCopy}>{current?.student_count ?? 0}{current?.student_limit ? ` of ${current.student_limit}` : ""} students in use</Text></View><Badge tone={current?.status === "ACTIVE" || current?.status === "TRIAL" ? "success" : "warning"}>{current?.status ?? "UNKNOWN"}</Badge></Card><Text style={styles.section}>Available plans</Text>{plans.data?.length ? plans.data.map((plan) => <Card key={plan.id} style={styles.plan}><View style={styles.planHeader}><Text style={styles.planName}>{plan.name}</Text>{plan.id === current?.plan?.id ? <Badge tone="success">CURRENT</Badge> : undefined}</View><Text style={styles.limit}>{plan.student_limit ? `Up to ${plan.student_limit} students` : "Flexible student limit"}</Text><Text style={styles.price}>₹{plan.monthly_price}<Text style={styles.period}> / month</Text></Text></Card>) : <EmptyState icon="⭐" title="No plans available" message="Subscription options will appear here when configured." />}</ScrollView></Screen>;
}
const styles = StyleSheet.create({ content: { gap: spacing.md, paddingBottom: spacing.xxl, paddingTop: spacing.lg }, current: { alignItems: "flex-start", backgroundColor: colors.ink, flexDirection: "row", justifyContent: "space-between" }, currentLabel: { color: "#b8c7f0", fontSize: 11, fontWeight: "800", letterSpacing: 1 }, currentName: { color: colors.white, fontSize: 25, fontWeight: "800", marginTop: spacing.xs }, currentCopy: { color: "#dbe5fc", fontSize: 13, marginTop: spacing.xs }, section: { ...typography.heading, fontSize: 17, marginTop: spacing.md }, plan: { borderColor: colors.line, borderWidth: 1 }, planHeader: { alignItems: "center", flexDirection: "row", justifyContent: "space-between" }, planName: { ...typography.heading, fontSize: 18 }, limit: { ...typography.body, fontSize: 13, marginTop: spacing.sm }, price: { ...typography.heading, color: colors.primary, fontSize: 24, marginTop: spacing.lg }, period: { ...typography.body, fontSize: 13 } });
