"""add requests and request comments tables

Revision ID: 41bbd7ae5c1f
Revises: 3b2c5d7e9f01
Create Date: 2026-10-09 13:11:23.752547
"""
from alembic import op
import sqlalchemy as sa


revision = '41bbd7ae5c1f'
down_revision = '3b2c5d7e9f01'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('requester_id', sa.Uuid(), nullable=False),
    sa.Column('request_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('decision_reason', sa.Text(), nullable=True),
    sa.Column('decided_by', sa.Uuid(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_requests_org_requester', 'requests', ['organization_id', 'requester_id'], unique=False)
    op.create_index('ix_requests_org_status', 'requests', ['organization_id', 'status'], unique=False)
    op.create_index(op.f('ix_requests_organization_id'), 'requests', ['organization_id'], unique=False)
    op.create_index(op.f('ix_requests_request_type'), 'requests', ['request_type'], unique=False)
    op.create_index(op.f('ix_requests_requester_id'), 'requests', ['requester_id'], unique=False)
    op.create_table('request_comments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('request_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_request_comments_request_id'), 'request_comments', ['request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_request_comments_request_id'), table_name='request_comments')
    op.drop_table('request_comments')
    op.drop_index(op.f('ix_requests_requester_id'), table_name='requests')
    op.drop_index(op.f('ix_requests_request_type'), table_name='requests')
    op.drop_index(op.f('ix_requests_organization_id'), table_name='requests')
    op.drop_index('ix_requests_org_status', table_name='requests')
    op.drop_index('ix_requests_org_requester', table_name='requests')
    op.drop_table('requests')
    # ### end Alembic commands ###
