"""add academic and subscription entities

Revision ID: 4435ac0de5c2
Revises: 9ca3628a19cc
Create Date: 2026-09-20 20:39:59.195924
"""
from alembic import op
import sqlalchemy as sa


revision = '4435ac0de5c2'
down_revision = '9ca3628a19cc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription_plans',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('monthly_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('annual_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('student_limit', sa.Integer(), nullable=True),
    sa.Column('teacher_limit', sa.Integer(), nullable=True),
    sa.Column('features', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('trial_ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['subscription_plans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id')
    )
    op.create_table('academic_tests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('class_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('subject', sa.String(length=120), nullable=True),
    sa.Column('test_date', sa.Date(), nullable=False),
    sa.Column('maximum_marks', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_academic_tests_class_id'), 'academic_tests', ['class_id'], unique=False)
    op.create_index(op.f('ix_academic_tests_organization_id'), 'academic_tests', ['organization_id'], unique=False)
    op.create_table('homework',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('class_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_homework_class_id'), 'homework', ['class_id'], unique=False)
    op.create_index(op.f('ix_homework_due_date'), 'homework', ['due_date'], unique=False)
    op.create_index(op.f('ix_homework_organization_id'), 'homework', ['organization_id'], unique=False)
    op.create_table('schedule_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('class_id', sa.Uuid(), nullable=False),
    sa.Column('teacher_id', sa.Uuid(), nullable=True),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.String(length=10), nullable=False),
    sa.Column('end_time', sa.String(length=10), nullable=False),
    sa.Column('room', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedule_entries_class_id'), 'schedule_entries', ['class_id'], unique=False)
    op.create_index(op.f('ix_schedule_entries_organization_id'), 'schedule_entries', ['organization_id'], unique=False)
    op.create_table('test_marks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('test_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('marks', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('grade', sa.String(length=20), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_id'], ['academic_tests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('test_id', 'student_id')
    )
    op.create_index(op.f('ix_test_marks_organization_id'), 'test_marks', ['organization_id'], unique=False)
    op.create_index(op.f('ix_test_marks_student_id'), 'test_marks', ['student_id'], unique=False)
    op.create_index(op.f('ix_test_marks_test_id'), 'test_marks', ['test_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_marks_test_id'), table_name='test_marks')
    op.drop_index(op.f('ix_test_marks_student_id'), table_name='test_marks')
    op.drop_index(op.f('ix_test_marks_organization_id'), table_name='test_marks')
    op.drop_table('test_marks')
    op.drop_index(op.f('ix_schedule_entries_organization_id'), table_name='schedule_entries')
    op.drop_index(op.f('ix_schedule_entries_class_id'), table_name='schedule_entries')
    op.drop_table('schedule_entries')
    op.drop_index(op.f('ix_homework_organization_id'), table_name='homework')
    op.drop_index(op.f('ix_homework_due_date'), table_name='homework')
    op.drop_index(op.f('ix_homework_class_id'), table_name='homework')
    op.drop_table('homework')
    op.drop_index(op.f('ix_academic_tests_organization_id'), table_name='academic_tests')
    op.drop_index(op.f('ix_academic_tests_class_id'), table_name='academic_tests')
    op.drop_table('academic_tests')
    op.drop_table('subscriptions')
    op.drop_table('subscription_plans')
    # ### end Alembic commands ###
