import { useState } from "react";
import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { useCreateGroupFee, useGroups, useStudents } from "@/api/hooks";
import { Button, Card, ErrorState, LoadingState, PageHeader, Screen, TuiroInput } from "@/components";
import { colors, spacing, typography } from "@/theme";

export default function CollectFeeScreen() {
    const groups = useGroups(); const students = useStudents(); const create = useCreateGroupFee(); const [target, setTarget] = useState<string>(""); const [individual, setIndividual] = useState(false); const [amount, setAmount] = useState(""); const [dueDate, setDueDate] = useState("");
    if (groups.isLoading || students.isLoading) return <Screen><LoadingState /></Screen>; if (groups.isError || students.isError) return <Screen><ErrorState onRetry={() => { void groups.refetch(); void students.refetch(); }} /></Screen>;
    const submit = async () => { if (!target || !Number(amount) || !dueDate) return Alert.alert("Complete the fee", "Choose a group (or individual student), amount and due date."); try { await create.mutateAsync(individual ? { student_id: target, amount: Number(amount), due_date: dueDate } : { group_id: target, amount: Number(amount), due_date: dueDate }); Alert.alert("Fee created", individual ? "This is an individual charge." : "It now applies to all active group members."); setTarget(""); setAmount(""); setDueDate(""); } catch { Alert.alert("Could not create fee", "Please check the entered details."); } };
    const choices = individual ? students.data ?? [] : groups.data ?? [];
    return <Screen><ScrollView contentContainerStyle={styles.list}><PageHeader eyebrow="FINANCE" title="Create fee" /><Text style={styles.help}>Start with a group. Use the individual path only for a one-off charge.</Text><View style={styles.mode}><Button variant={individual ? "ghost" : "secondary"} onPress={() => { setIndividual(false); setTarget(""); }}>Group</Button><Button variant={individual ? "secondary" : "ghost"} onPress={() => { setIndividual(true); setTarget(""); }}>Individual student</Button></View><Text style={styles.help}>{individual ? "Choose student" : "Choose group"}</Text>{choices.map((item) => <Pressable key={item.id} onPress={() => setTarget(item.id)}><Card style={[styles.fee, target === item.id && styles.feeSelected]}><Text style={styles.name}>{"name" in item ? item.name : `${item.first_name} ${item.last_name}`}</Text><Text style={styles.meta}>{"student_count" in item ? `${item.student_count} active students` : item.grade ?? "Student"}</Text></Card></Pressable>)}<TuiroInput label="Amount" keyboardType="decimal-pad" value={amount} onChangeText={setAmount} placeholder="0" /><TuiroInput label="Due date (YYYY-MM-DD)" value={dueDate} onChangeText={setDueDate} placeholder="2026-10-01" /><Button disabled={create.isPending} onPress={() => void submit()}>{create.isPending ? "Creating..." : "Create fee"}</Button></ScrollView></Screen>;
}
const styles = StyleSheet.create({ list: { gap: spacing.sm, paddingBottom: spacing.xxl, paddingTop: spacing.lg }, name: { ...typography.heading, fontSize: 16 }, meta: { ...typography.body, fontSize: 12, marginTop: 4 }, help: { ...typography.body }, mode: { flexDirection: "row", gap: spacing.sm }, fee: { padding: spacing.md }, feeSelected: { borderColor: colors.primary, borderWidth: 2 } });
